### ISSUE TITLE
Which plugin to use with watch command?

### ISSUE THREAD

**Issue by smartaquarius10** [maniSbindra/k8s-delete-validation-webhook#7]
Hello @maniSbindra 
Hope you're doing well. 

In your [session ](https://www.youtube.com/watch?v=d0Yq5vU_maQ) of admission webhooks the output of watch command is updating at the same place without appending the output. Could you please suggest that how to do that because the appending format of watch flags is pretty frustrating. 

Thanks.

**Comment by maniSbindra** [comment]
Hi @smartaquarius10 ,

watch -n $periodInSeconds "command" will normally refresh the output every $periodInSeconds seconds. Could you share the exact command you are executing?

**Comment by smartaquarius10** [comment]
Hey @maniSbindra ,

I generally use kubectl arguments **-w**

So in that it keeps on appending

Kind Regards,
Tanul

**Comment by smartaquarius10** [comment]
Thanks @maniSbindra , Closing the query.. Happy weekend :)
